[Content]
RemovePackages=
        dracut
        libmagic1
        file-magic
        file
        openSUSE-build-key
        shim
        systemd-boot
        update-bootloader
# Cleanup files we don't need on an installer
RemoveFiles=
        /var/*
        /boot
        /usr/include
        /usr/share/locale
